### ISSUE TITLE
support operator for knative

### ISSUE THREAD

**Issue by jstrachan** [jx3-gitops-repositories/jx3-kubernetes-istio#1]
we should improve the chart / version stream so we can more easily setup the operator correctly for knative
see: 
https://kubernetes.slack.com/archives/C9LTHT2BB/p1609870135179300?thread_ts=1609817231.171500&cid=C9LTHT2BB

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-main
spec:
  profile: default
  values:
    global:
      proxy:
        autoInject: enabled
      useMCP: false
      # The third-party-jwt is not enabled on all k8s.
      # See: https://istio.io/docs/ops/best-practices/security/#configure-third-party-service-account-tokens
      jwtPolicy: first-party-jwt
  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          serviceAnnotations:
            service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
            external-dns.alpha.kubernetes.io/hostname: '*.{{ .Values.jxRequirements.ingress.domain }}'
      - name: cluster-local-gateway
        enabled: true
        label:
          istio: cluster-local-gateway
          app: cluster-local-gateway
        k8s:
          service:
            type: ClusterIP
            ports:
            - port: 15020
              name: status-port
            - port: 80
              targetPort: 8080
              name: http2
            - port: 443
              targetPort: 8443
              name: https
```
